name: Release

on:
  push:
    tags:
      - 'unvenv-v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#unvenv-}
          echo "version=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "version_number=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Release
        run: |
          gh release create ${{ steps.version.outputs.version }} \
            --title "unvenv ${{ steps.version.outputs.version_number }}" \
            --notes "Release ${{ steps.version.outputs.version_number }}" \
            --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: unvenv
          target: ${{ matrix.target }}
          include: LICENSE,README.md,CLAUDE.md
          tar: none
          tar-xz: none
          zip: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}